name: CI devops 2022 EPF
on:
  #to begin you want to launch this job in main and develop
  push:
    branches: [master]
  pull_request:

jobs:
  test-backend: 
    name: backend
build-and-push-docker-image:  
    needs: test-backend
    runs-on: ubuntu-latest
    
    steps:
      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
    
     #checkout your github code using actions/checkout@v2.3.3
      - name: Checkout repository
        uses: actions/checkout@v2.3.3
        
      - name: Build image and push backend
        uses: docker/build-push-action@v2
        with:
          context: ./simple-api
          tags: ${{secrets.DOCKERHUB_USERNAME}}/correction-tp1-devops/simple-api
          push: ${{ github.ref == 'refs/heads/main }}

     - name: Build image and push database
       uses: docker/build-push-action@v2
       with:
         context: ./database
         tags: ${{secrets.DOCKERHUB_USERNAME}}/correction-tp1-devops/database
         push: ${{ github.ref == 'refs/heads/main }}
     
     - name: Build and push http
       uses: docker/build-push-action@v2
       with:
         context: ./http
         tags: ${{secrets.DOCKERHUB_USERNAME}}/correction-tp1-devops/http
         push: ${{ github.ref == 'refs/heads/main }}
